export const groups = [
  {
    id: 0,
    name: 'Hines Supply',
    welcomeText: 'Welcome to the Hines Supply App!',
    logo: '../assets/logo_1.png',
    returnLabel: 'Return to Hines',
    returnLink: '/',
  },
  {
    id: 1,
    name: 'Bellevue Builders Supply',
    welcomeText: 'Welcome to the\nBellevue Builders Supply App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to BBS',
    returnLink: '/',
  },
  {
    id: 2,
    name: 'Building Supply Association',
    welcomeText: 'Welcome to the\nBuilding Supply Association App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to BSA',
    returnLink: '/',
  },
  {
    id: 3,
    name: 'Coastal Roofing Supply',
    welcomeText: 'Welcome to the\nCoastal Roofing Supply App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to CRS',
    returnLink: '/',
  },
  {
    id: 4,
    name: 'GBS Building Supply',
    welcomeText: 'Welcome to the\nGBS Building Supply App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to GBS',
    returnLink: '/',
  },
  {
    id: 5,
    name: 'East Haven Builders Supply',
    welcomeText: 'Welcome to the\nEast Haven Builders Supply App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to EHBS',
    returnLink: '/',
  },
  {
    id: 6,
    name: 'Jones Lumber Co.',
    welcomeText: 'Welcome to the\nJones Lumber Co. App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to Jones',
    returnLink: '/',
  },
  {
    id: 7,
    name: 'Myers',
    welcomeText: 'Welcome to the Myers App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to Myers',
    returnLink: '/',
  },
  {
    id: 8,
    name: 'KI',
    welcomeText: 'Welcome to the KI App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to KI',
    returnLink: '/',
  },
  {
    id: 9,
    name: 'Wisconsin Building Supply',
    welcomeText: 'Welcome to the\nWisconsin Building Supply App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to WBS',
    returnLink: '/',
  },
  {
    id: 10,
    name: 'Universal Supply Co.',
    welcomeText: 'Welcome to the\nUniversal Supply Co. App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to USC',
    returnLink: '/',
  },
  {
    id: 11,
    name: 'Poulin Lumber',
    welcomeText: 'Welcome to the Poulin Lumber App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to PL',
    returnLink: '/',
  },
  {
    id: 12,
    name: 'Shelly’s Building Supply',
    welcomeText: 'Welcome to the\nShelly’s Building Supply App!',
    logo: '../assets/logo_2.png',
    returnLabel: 'Return to Shelly’s',
    returnLink: '/',
  },
];

export const appSettings = {
  activeGroupId: 11,
};

export const BASE_API_URL = 'https://tc-usb-api.herokuapp.com';
